authors:
  <author>:
    name: Yaulande Douanla       # Author name
    description: Dr in Climate Science and Atmospheric Physics # Author description
    # <!-- avatar: url         # Author avatar -->
    # <!-- slug: url           # Author profile slug -->
    # <!-- url: url            # Author website URL -->